apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/opensearch
    repoURL: https://github.com/pbak-pjatk/test-deployment.git #TODO Update me
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true